# zone_settings.py
# Stores static zone-related dictionaries for use in ZoneDB and other modules

ZONE_LEVEL_CHART = {
    'abysmal': '1 - 65',
    'acrylia': '50 - 60',
    'airplane': '50 - 60',
    'akanon': '1 - 10',
    'akheva': '55 - 60',
    'arcstone': '65 - 75',
    'bazaar': '1 - 65',
    'befallen': '5 - 20',
    'beholder': '35 - 40',
    'blackburrow': '5 - 15',
    'bloodfields': '60 - 65',
    'buriedsea': '65 - 75',
    'burningwood': '50 - 60',
    'butcher': '1 - 20',
    'cabeast': '1 - 75',
    'cabwest': '1- 75',
    'cauldron': '15 - 25',
    'cazicthule': '40 - 60',
    'charasis': '50 - 60',
    'chardok': '50 - 60',
    'citymist': '45 - 55',
    'commons': '10 - 50',
    'corathus': '50 - 65',
    'cragstone': '20 - 30',
    'crescent': '1 - 20',
    'crushbone': '5 - 15',
    'cryptofshade': '65 - 70',
    'dalnir': '35 - 45',
    'devastation': '65 - 75',
    'dragonlair': '60 - 65',
    'dragonscale': '70 - 80',
    'dranik': '60 - 65',
    'draniksscar': '60 - 65',
    'dreadlands': '45 - 60',
    'droga': '35 - 50',
    'drowned': '50 - 65',
    'eastkarana': '15 - 25',
    'eastwastes': '35 - 50',
    'ecommons': '5 - 15',
    'emeraldjungle': '45 - 55',
    'erudnext': '1 - 10',
    'erudnint': '1 - 10',
    'erudsxing': '10 - 20',
    'everfrost': '1 - 10',
    'fearplane': '50 - 60',
    'feerrott': '1 - 10',
    'felwithea': '1 - 10',
    'fieldofbone': '1 - 20',
    'firiona': '30 - 40',
    'freporte': '1 - 10',
    'freportw': '1 - 10',
    'frontiermtns': '35 - 45',
    'frozenshadow': '30 - 50',
    'fungusgrove': '50 - 60',
    'gfaydark': '1 - 15',
    'griegsend': '55 - 60',
    'grobb': '1-75',
    'growthplane': '50 - 60',
    'halas': '1 - 10',
    'harbingers': '60 - 65',
    'hateplaneb': '50 - 60',
    'highkeep': '20 - 30',
    'highpass': '10-20',
    'hohonora': '60 - 65',
    'hohonorb': '60 - 65',
    'hole': '45 - 60',
    'iceclad': '25 - 40',
    'innothule': '5 - 15',
    'kael': '50 - 60',
    'kaladima': '1 - 10',
    'kaladimb': '1 - 10',
    'karnor': '45 - 60',
    'kedge': '45 - 55',
    'kelethin': '1 - 10',
    'kerraridge': '10 - 20',
    'kithicor': '10 - 50',
    'lakeofillomen': '15 - 30',
    'lakerathe': '10 - 25',
    'lavastorm': '5 - 15',
    'lfaydark': '10 - 25',
    'maiden': '50 - 60',
    'mesa': '35 - 55',
    'mischiefplane': '50 - 60',
    'misty': '1 - 10',
    'moors': '30 - 45',
    'mseru': '35 - 50',
    'najena': '15 - 25',
    'nektulos': '5 - 15',
    'neriaka': '1 - 10',
    'neriakb': '1 - 10',
    'neriakc': '1 - 10',
    'netherbian': '30 - 45',
    'northkarana': '10 - 20',
    'nro': '5 - 15',
    'oggok': '1 - 10',
    'oldhighpass': '10 - 20',
    'oldkurn': '10 - 25',
    'oot': '10 - 20',
    'overthere': '25 - 40',
    'paineel': '1 - 10',
    'paludal': '15 - 30',
    'paw': '30 - 40',
    'poair': '65 - 70',
    'podisease': '50 - 60',
    'poearthb': '65 - 70',
    'pofire': '65 - 70',
    'poinnovation': '50 - 60',
    'pojustice': '45 - 55',
    'poknowledge': '1 - 65',
    'ponightmare': '50 - 60',
    'postorms': '55 - 65',
    'potactics': '60 - 65',
    'potimeb': '65 - 70',
    'potorment': '60 - 65',
    'potranquility': '1 - 65',
    'povalor': '55 - 65',
    'powater': '65 - 70',
    'provinggrounds': '60 - 65',
    'qcat': '5 - 15',
    'qey2hh1': '10 - 20',
    'qeynos': '1 - 10',
    'qeynos2': '1 - 10',
    'qeytoqrg': '1 - 10',
    'qrg': '1 - 10',
    'rathemtn': '15 - 30',
    'riftseekers': '65 - 70',
    'rivervale': '1 - 10',
    'scarlet': '35 - 50',
    'sebilis': '55 - 60',
    'sirens': '50 - 60',
    'skyfire': '50 - 60',
    'sleeper': '60 - 65',
    'soldunga': '20 - 30',
    'soldungb': '40 - 60',        
    'soltemple': '35 - 45',
    'southkarana': '20 - 30',
    'sro': '15 - 25',
    'sseru': '45 - 55',
    'ssratemple': '55 - 60',
    'steamfactory': '70 - 80',
    'steamfont': '1 - 15',
    'steamfontmts': '1 - 15',
    'steppes': '70 - 80',
    'swampofnohope': '20 - 35',
    'templeveeshan': '60 - 65',
    'tenebrous': '25 - 40',
    'thedeep': '45 - 60',
    'thegrey': '45 - 55',
    'thurgadina': '1 - 10',
    'timorous': '25 - 40',
    'toxxulia': '1 - 10',
    'trakanon': '45 - 55',
    'twilight': '45 - 55',
    'umbral': '55 - 60',
    'unrest': '15 - 30',
    'wakening': '45 - 60',
    'wallofslaughter': '60 - 65',
    'warrens': '15 - 30',
    'westwastes': '55 - 60',
}

continent_zones = {
    'Antonica': [
        'befallen', 'beholder', 'blackburrow', 'cazicthule', 'commons', 'eastkarana', 'ecommons', 'everfrost', 'feerrott',
        'freporte', 'freportn', 'freportw', 'grobb', 'gukbottom', 'guktop', 'halas', 'highkeep', 'highpass',
        'innothule', 'kithicor', 'lakerathe', 'lavastorm', 'misty', 'najena', 'nektulos', 'neriakb', 'neriaka',
        'neriakc', 'neriakd', 'northkarana', 'nro', 'oasis', 'oggok', 'oot', 'paw', 'permafrost', 'qcat', 'qey2hh1',
        'qeynos', 'qeynos2', 'qeytoqrg', 'qrg', 'rathemtn', 'rivervale', 'runnyeye', 'soldunga', 'soldungb', 'soldungc',
        'soltemple', 'southkarana', 'sro'
    ],
    'Faydwer': [
        'akanon', 'butcher', 'cauldron', 'crushbone', 'felwithea', 'felwitheb', 'gfaydark', 'kaladima', 'kaladimb',
        'kedge', 'lfaydark', 'mistmoore', 'steamfont', 'unrest'
    ],
    'Odus': [
        'erudnext', 'erudnint', 'erudsxing', 'hole', 'kerraridge', 'paineel', 'stonebrunt', 'tox', 'warrens'
    ],
    'Kunark': [
        'burningwood', 'cabeast', 'cabwest', 'chardok', 'chardokb', 'charasis', 'citymist', 'dalnir', 'dreadlands', 'droga',
        'emeraldjungle', 'fieldofbone', 'firiona', 'frontiermtns', 'howlingstones', 'kaesora', 'karnor', 'kurn',
        'lakeofillomen', 'nurga', 'overthere', 'sebilis', 'skyfire', 'swampofnohope', 'timorous', 'trakanon',
        'veeshan', 'veksar', 'warslikswood'
    ],
    'Velious': [
        'cobaltscar', 'crystal', 'dragonnecrop', 'eastwastes', 'frozenshadow', 'greatdivide', 'growthplane',
        'iceclad', 'kael', 'necropolis', 'sirens', 'skyshrine', 'sleeper', 'templeveeshan', 'thurgadina',
        'thurgadinb', 'towerfrozen', 'velketor', 'wakening', 'westwastes'
    ],
    'Luclin': [
        'acrylia', 'akheva', 'bazaar', 'dawnshroud', 'echo', 'fungusgrove', 'griegsend', 'grimling', 'hollowshade',
        'jaggedpine', 'katta', 'letalis', 'maiden', 'marusseru', 'mseru', 'netherbian', 'nexus', 'paludal',
        'scarlet', 'shadeweaver', 'shadowhaven', 'sharvahl', 'sseru', 'ssratemple', 'tenebrous', 'thedeep',
        'thegrey', 'twilight', 'umbral', 'vexthal'
    ],
    'Planes': [
        'airplane', 'bothunder', 'codecay', 'fearplane', 'hateplane', 'hateplaneb', 'hohonora', 'hohonorb',
        'mischiefplane', 'nightmareb', 'podisease', 'poair', 'poeartha', 'poearthb', 'pofire', 'pohonora',
        'pohonorb', 'poinnovation', 'pojustice', 'poknowledge', 'ponightmare', 'postagnation', 'postorms',
        'potactics', 'potimea', 'potimeb', 'potorment', 'pothunder', 'potranquility', 'povalor', 'powar',
        'powater', 'solrotower'
    ],
    'Broken Skull Rock': [
        'dulak','hatesfury','nadox','gunthak','torgiran'
    ]
} 